import { executeSql, rowsFromSql, listTables } from "./runtime-client";
import type { AnalyticEvent, LogStats } from "./analytics";
import { aggregateLogs } from "./analytics";
import type { AccessLogLine } from "./access-log";

/**
 * Analytics backed by Librebase's own runtime Postgres (the project instance).
 *
 * The dashboard's source of truth is the Librebase runtime: request traffic
 * arrives as the access-log JSONL, and the events/todos the agent writes are
 * stored in a dedicated schema inside the project's own Postgres (via /v1/sql).
 * There is no external Supabase dependency on this path.
 */

const SCHEMA = "librebase_analytics";

const BOOTSTRAP = `
create schema if not exists ${SCHEMA};
create table if not exists ${SCHEMA}.events (
  id bigint generated by default as identity primary key,
  kind text not null,                 -- 'request' | 'login' | 'todo' | 'agent_step'
  severity text not null default 'info',
  status integer,
  path text,
  method text,
  event text,
  data jsonb,
  created_at timestamptz not null default now()
);
create table if not exists ${SCHEMA}.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
`;

async function ensureSchema(projectId: string): Promise<boolean> {
  const res = await executeSql(projectId, BOOTSTRAP);
  return res.ok;
}

export type LibrebaseAnalyticsResult<T> = {
  ok: boolean;
  data: T;
  message?: string;
};

export async function initAnalyticsSchema(
  projectId: string,
): Promise<{ ok: boolean; message?: string }> {
  const ok = await ensureSchema(projectId);
  return {
    ok,
    message: ok ? undefined : "Runtime SQL is not available; analytics stay local until it is.",
  };
}

/** Record one event into the project's own Postgres (best-effort). */
export async function recordEvent(
  projectId: string,
  event: Omit<AnalyticEvent, "orgId" | "projectId">,
): Promise<void> {
  try {
    await ensureSchema(projectId);
    await executeSql(
      projectId,
      `insert into ${SCHEMA}.events (kind, severity, status, path, method, event, data)
       values (
         '${event.kind.replace(/'/g, "''")}',
         '${(event.severity ?? "info").replace(/'/g, "''")}',
         ${event.status ?? "null"},
         ${quote(event.path)},
         ${quote(event.method)},
         ${quote(event.event)},
         ${event.data ? `'${JSON.stringify(event.data).replace(/'/g, "''")}'::jsonb` : "null"}
       )`,
    );
  } catch {
    // best-effort
  }
}

export async function addTodo(
  projectId: string,
  title: string,
): Promise<void> {
  try {
    await ensureSchema(projectId);
    await executeSql(
      projectId,
      `insert into ${SCHEMA}.todos (title) values (${quote(title)})`,
    );
  } catch {
    // best-effort
  }
}

export type TodoRow = {
  id: number;
  title: string;
  done: boolean;
  createdAt: string;
};

export async function listTodosFromRuntime(
  projectId: string,
): Promise<LibrebaseAnalyticsResult<TodoRow[]>> {
  const res = await executeSql(
    projectId,
    `select id, title, done, created_at as "createdAt"
     from ${SCHEMA}.todos order by created_at desc limit 50`,
  );
  if (!res.ok) {
    return { ok: false, data: [], message: "Runtime SQL unavailable for todos." };
  }
  const rows = rowsFromSql(res.body);
  return {
    ok: true,
    data: rows.map((r) => ({
      id: Number(r.id ?? 0),
      title: String(r.title ?? ""),
      done: Boolean(r.done),
      createdAt: String(r.createdAt ?? ""),
    })),
  };
}

/** Row counts by kind + error/login totals persisted in the runtime. */
export type RuntimeCounts = {
  byKind: Record<string, number>;
  errors: number;
  logins: number;
};

export async function runtimeCounts(
  projectId: string,
): Promise<LibrebaseAnalyticsResult<RuntimeCounts>> {
  const res = await executeSql(
    projectId,
    `select kind, count(*) as n
     from ${SCHEMA}.events group by kind`,
  );
  if (!res.ok) {
    return { ok: false, data: { byKind: {}, errors: 0, logins: 0 } };
  }
  const byKind: Record<string, number> = {};
  for (const r of rowsFromSql(res.body)) {
    const kind = String(r.kind ?? "other");
    byKind[kind] = Number(r.n ?? 0);
  }
  return {
    ok: true,
    data: {
      byKind,
      errors: byKind.error ?? 0,
      logins: byKind.login ?? 0,
    },
  };
}

/** Total persisted request events + todos. */
export async function runtimeTotals(
  projectId: string,
): Promise<LibrebaseAnalyticsResult<{ events: number; todos: number; doneTodos: number }>> {
  const res = await executeSql(
    projectId,
    `select
       (select count(*) from ${SCHEMA}.events) as events,
       (select count(*) from ${SCHEMA}.todos) as todos,
       (select count(*) from ${SCHEMA}.todos where done) as done_todos`,
  );
  if (!res.ok) return { ok: false, data: { events: 0, todos: 0, doneTodos: 0 } };
  const rows = rowsFromSql(res.body);
  const r = rows[0] ?? {};
  return {
    ok: true,
    data: {
      events: Number(r.events ?? 0),
      todos: Number(r.todos ?? 0),
      doneTodos: Number(r.done_todos ?? 0),
    },
  };
}

function quote(value: string | null | undefined): string {
  if (value == null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

export { aggregateLogs };
export type { AccessLogLine, LogStats };
