[package]
name = "li-container-cri"
version = "0.1.2"
edition = "2026"
license = "GPL-3.0-or-later"
description = "licri — Kubernetes CRI shim (Li)"

[dependencies]
li-container = { path = "../li-container" }
li-containerd = { path = "../li-containerd" }

[package.metadata.li]
import_name = "container.cri"
min_lic = "0.1.0"
maintainer = "librebase-official"
pkg_id = "PKG-li-container-cri"
