[workspace]
resolver = "2"
members = [
    "licontainer-proto",
    "lirun",
    "liimg",
    "licontainerd",
    "lictl",
    "licri",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Julian M. Kleber <julian.kleber@sail.black>"]
repository = "https://github.com/librebase-official/librebase"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
licontainer-proto = { path = "licontainer-proto" }
