[package]
name = "li-containerd"
version = "0.1.5"
edition = "2026"
license = "GPL-3.0-or-later"
description = "licontainerd — container daemon (Li)"

[dependencies]
li-container = { path = "../li-container" }
li-container-img = { path = "../li-container-img" }

[package.metadata.li]
import_name = "container.daemon"
min_lic = "0.1.0"
maintainer = "librebase-official"
pkg_id = "PKG-li-containerd"
