[package]
name = "li-container-run"
version = "0.1.11"
edition = "2026"
license = "GPL-3.0-or-later"
description = "lirun — OCI runtime (Li)"

[dependencies]
li-container = { path = "../li-container" }

[package.metadata.li]
import_name = "container.run"
min_lic = "0.1.0"
maintainer = "librebase-official"
pkg_id = "PKG-li-container-run"
