[package]
name = "lictl"
description = "CLI for licontainer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "lictl"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
licontainer-proto = { workspace = true }

[target.'cfg(windows)'.dependencies]
which = "7"

[dev-dependencies]
tempfile = "3"
