apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if eq .Values.deploymentMode "shared" }}librebase-config-{{ .Values.instanceId }}{{ else }}librebase-config{{ end }}
  namespace: {{ include "librebase.namespace" . }}
  labels:
    {{- include "librebase.labels" . | nindent 4 }}
data:
  LI_DATA_DIR: "/data"
  LIDB_RUNTIME_MODE: {{ .Values.runtimeMode | quote }}
  LIBREBASE_API_PORT: {{ .Values.ports.api | quote }}
  LIBREBASE_PG_PORT: {{ .Values.ports.postgres | quote }}
  LIBREBASE_INSTANCE_ID: {{ .Values.instanceId | quote }}
  LIBREBASE_ORG_ID: {{ .Values.orgId | quote }}
