import { NextResponse } from "next/server";
import { executeSql, listTables } from "@/lib/runtime-client";
import { probeProjectDb } from "@/lib/project-runtime";

interface RouteParams {
  params: Promise<{ projectId: string }>;
}

export async function GET(request: Request, { params }: RouteParams) {
  const { projectId } = await params;
  const schema = new URL(request.url).searchParams.get("schema") ?? "public";
  const result = await listTables(projectId, schema);
  return NextResponse.json(result);
}

export async function POST(request: Request, { params }: RouteParams) {
  const { projectId } = await params;
  const probe = await probeProjectDb(projectId);
  if (!probe.reachable) {
    return NextResponse.json({ error: "Project is paused" }, { status: 409 });
  }
  const body = (await request.json()) as {
    name?: string;
    schema?: string;
    rls?: boolean;
  };
  const name = body.name?.trim();
  if (!name || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    return NextResponse.json({ error: "Valid table name required" }, { status: 400 });
  }
  const schema = (body.schema ?? "public").replace(/"/g, "");
  const sql = [
    `CREATE TABLE "${schema}"."${name}" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now())`,
    body.rls === false ? "" : `ALTER TABLE "${schema}"."${name}" ENABLE ROW LEVEL SECURITY`,
  ]
    .filter(Boolean)
    .join(";\n");
  const result = await executeSql(projectId, sql);
  return NextResponse.json(result, { status: result.ok ? 201 : 502 });
}
